
export const LOAD_SERVICES = 'LOAD_SERVICES';   
export const LOADING_SERVICES = 'LOADING_SERVICES';
export const LOADED_SERVICES = 'LOADED_SERVICES';

export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
